### PR TITLE
Fix gs v2

### PR DESCRIPTION
**Pull request by rsa2135**
fixes #31 
Addressed prior comments

### CODE REVIEW

**Comment by shinriyo** [comment]
@rsa2135 Thank you for your pull-request again.
But, `ga` command has a bug.

```
> gs
# On branch: master
#
#
➤ Changes not staged for commit:
#
#        modified: [1] LICENSE
#
> ga 1
fatal: pathspec '/Users/shinriyo/development/breeze/fix-gs-v2' did not match any files
```

I'm looking for your code. Could you fix it?

**Comment by rsa2135** [comment]
Good catch. I forgot to add a statement to reset the global `arr` upon every function invocation. This is exactly where tests would shine. I hope to get around adding coverage to other functions.

Screen Shot 2020-04-27 at 8 21 52 PM

**Comment by shinriyo** [comment]
@rsa2135 Thank you for quick fix and contribution!

I'd like to know how to run the fish test code.

**Comment by rsa2135** [comment]
@shinriyo, of course!
First, you'll need to install [Fishtap](https://github.com/jorgebucaran/fishtape) (test runner) and [fish-mock](https://github.com/matchai/fish-mock) (mocking library).  
Then, simply `cd` into the test directory and run `fishtape ./gs_test.fish`

**Comment by shinriyo** [comment]
@rsa2135 
Thank you for telling me that.

**Comment by shinriyo** [comment]
[LGTM](https://www.lgtm.app/i/zEcmN53Tr)

**Pull request merged**
