### PR TITLE
Add alias information to simple functions

### PR DESCRIPTION
**Pull request by bingocaller**
This lets users see all the aliases (at least the simple ones 😅)
added by breeze by running [`alias`](https://fishshell.com/docs/current/cmds/alias.html).

### CODE REVIEW

**Comment by shinriyo** [comment]
```
> git fetch origin pull/32/head:add-alias-information

> gb
  [1] add-alias-information
* [2] master

> gco 1
> fisher add .

> alias                                      Fri Apr 24 12:46:31 2020
alias cdgtop 'cd (git rev-parse --show-toplevel)'
alias g git
alias gaa 'git add --all'
alias gap 'git add -p'
alias gash 'git stash'
alias gasha 'git stash apply'
alias gashl 'git stash list'
alias gashp 'git stash pop'
alias gashu 'git stash --include-untracked'
alias gau 'git add -u'
alias gc 'git commit'
alias gce 'git clean'
alias gcef 'git clean -fd'
alias gcl 'git clone'
alias gcmsg 'git commit -m'
alias gdf 'git diff --'
alias gdnw 'git diff -w --'
alias gdw 'git diff --word-diff'
alias gf 'git fetch'
alias gfa 'git fetch --all'
alias gfr 'git fetch; and git rebase'
alias glg 'git log --graph --max-count=5'
alias gm 'git merge'
alias gmff 'git merge --ff'
alias gmnff 'git merge --no-ff'
alias gopen 'git config --get remote.origin.url | xargs open'
alias gpl 'git pull'
alias gplr 'git pull --rebase'
alias gps 'git push'
alias gpsf 'git push -f'
alias gr 'git remote -v'
alias grb 'git rebase'
alias grbi 'git rebase -i'
alias grs 'git reset --'
alias grsh 'git reset --hard'
alias grsl 'git reset HEAD~'
alias gsh 'git show'
alias gt 'git tag'
alias gtop 'git rev-parse --show-toplevel'
alias gurl 'git config --get remote.origin.url'
alias runsv 'python -m SimpleHTTPServer'
```

**Comment by shinriyo** [comment]
@bingocaller 

Thank you for your contribution.
I have never known the alias future.

**Comment by shinriyo** [comment]
LGTM

**Comment by bingocaller** [comment]
You're welcome and thank you for porting breeze to fish! It was one of the biggest reasons why I've been putting off switching from zsh! 😊

**Pull request merged**
