### PR TITLE
Fix gs

### LINKED ISSUE #30: gs lacks parsing of all short-hand permutations
### Issue description
Currently `gs` only covers a handful (of the more common) status permutation that can occur between the working tree and the index. Specifically, `??`, ` M`, ` M`, `MM`, `D`, ` D`, `DD`, `R`, ` A`, and `A `.
For all other short-hand permutations, an error is printed to the screen— `TODO: UNKNOWN. FIX LATER...`
Furthermore, many of the parsed statuses will not appear in all relevant states (to be committed, and not staged), but only in one.

### Steps to reproduce the issue

1. Bring a file in your current branch to a permutation that is not supported. 
For example, a `git status --porcelain` output of `AD added to index, deleted in tree.txt.txt` and then 

2. run `gs`

### What's the expected result?
```
➤ Changes to be committed:

#        new file:  [1] added to index, deleted in tree.txt

➤ Changes not staged for commit:

#         deleted: [2] added to index, deleted in tree.txt
```

### What's the actual result?
```
➤ Changes to be committed:

AD "added to index, deleted in tree.txt"
TODO: UNKNOWN. FIX LATER...
```

### Additional details / screenshot
Here's an example of an output the shows quite a few of these issues
before

### PR DESCRIPTION
**Pull request by rsa2135**
resolves #30 
### Summary of changes:

1. Statuses are now grouped by state and not scattered
2. Added logic to handle all possible statuses permutations
	* including ignored and unmerged paths
3. Tightened up output
	* Colors are not consistent across states
	* Numbering alignments — numbers are now right-aligned when more than 1 digits long
	* removed source -> destination from renames that are not changed to commit (rename is not tracked)
	* removed extraneous quotes from filenames
4. Allowed for certain flags, e.g. `—ignored`, `—renames`, and  `—no-renames`
5. Added tests
	* Current coverage is only for `gs.fish`
	* Tests are running via `Fishtape` and are using  `fish-mock`

### CODE REVIEW

**Comment by shinriyo** [comment]
@rsa2135
Thank you for your contribution.

I tried your code.
But, It effected `ga` command.
Screen Shot 2020-04-24 at 22 21 31

I am waiting for marge.

**Comment by rsa2135** [comment]
Somewhere along the process, some of the character encodings changed. Specifically, ASCII's apostrophe and quotation-mark changed to Unicode's single and double quotation marks which were affecting the regex (and some of the tests). I'm not sure what caused it, perhaps my text-editor or note-taking app. Anyways, I fixed both and it should be working again.

**Comment by shinriyo** [comment]
@rsa2135 Cool.
Thank you for resolve.

**Comment by shinriyo** [comment]
LGTM

**Comment by shinriyo** [comment]
@rsa2135 
I'm sorry. I found other bug about `gco` command.
So, I reverted.

```
> gco 1
error: pathspec '?[32m#        modified: ?[30m?(B?[m/idx/ ?[32mLICENSE' did not match any file(s) known to git
```

**Comment by rsa2135** [comment]
Unbeknownst to me, the changes I made to global `arr` were causing other functions to fail. To solve the issue I reverted the changes I made to the global `arr` and `ga.fish`. All changes I made are now contained only in `gs.fish`, so all functionality that was working before should be working currently.

**Pull request merged**
