### PR TITLE
Convert simple alias functions to abbreviations

### LINKED ISSUE #41: Consider converting simple aliases to abbreviations
## What?
Since fish supports [abbreviations](https://fishshell.com/docs/current/cmds/abbr.html), perhaps we should convert the simple aliases (like `gf` for `git fetch`) to abbreviations?  
For example, with an abbreviation in place, the input <kbd>g</kbd> <kbd>f</kbd> <kbd>Space</kbd> will result in the full text `git fetch ` on the command line; from here the user can keep typing to append stuff to the command. Alternatively, if the user ends the abbreviation with <kbd>Enter</kbd>, the full text gets unfolded and the command is issued immediately.

## Why?
1. I think this would be helpful for users to see which git commands are actually being run and also make command history more searchable (it's probably easier to remember to search for `git rebase` rather than `grb`).
2. We don't flood the user's `functions` directory with non-namespaced functions.
3. It might eliminate the need for custom completions.
4. See more pros and cons in fish-shell/fish-shell#731

## However!
Depending on how we handle it, this might be a breaking change if people use their breeze aliases inside functions or other aliases.

Also, I'm not entirely sure how to get this to the users since each abbreviation is stored as a global or universal variable and not as a function. Maybe we can add it in a `conf.d` script which runs as part of the `fisher` install process?

### PR DESCRIPTION
**Pull request by bingocaller**
Add conf.d/breeze.fish script, which initialises all simple
abbreviations and removes them on uninstall.
Remove replaced alias functions.
Remove git completions file, which should no longer be needed.

~~**Bonus feature:**
Move custom breeze functions from `<shortened name>.fish` to
`_breeze_<full(ish) name>.fish`
Add `<shortened name>` abbreviation for each custom breeze function.~~

Resolves #41

### CODE REVIEW

**Comment by shinriyo** [comment]
ezgif-1-7c631e29e497
I checked out it.
Is it automatically show original command when I hit enter key?

**Comment by bingocaller** [comment]
Yes, exactly! 🙂
I only did it for the alias-like functions where the abbreviation maps directly to an expanded command, so the following ones that have more custom functionality don't expand:  
* `ga`
* `gb`
* `gbl`
* `gbu`
* `gco`
* `gd`
* `gl`
* `grm`
* `gs`

**Comment by bingocaller** [comment]
I was also thinking we could name space the remaining breeze functions and add abbreviations for them. So, for example, `gd` would expand to `_breeze_git_diff`.   I think this could help users understand/remember when they are running a custom breeze function, make them more findable in history, and better group them in the user's `functions` folder. Let me know what you think! 🙂

**Comment by bingocaller** [comment]
My latest commit includes name spacing of custom functions in case we want to include this.

**Comment by shinriyo** [comment]
@bingocaller 

output
I tried. but, auto-complementary shows the function name.
Users may surprise about it. I guess the original git function should appear. 
Do you know how to fix this?

**Comment by bingocaller** [comment]
Yes, that was my intention. I thought it might reduce confusion about which functions are being run, but it seems that is not the case. 😅  
If we want the abbreviations to expand to `git <command>` while still doing the file shortcuts we would have to overload `git` somehow. We could potentially do that, but I think it's out of scope for this PR. I'd be up for doing a separate PR with a suggestion for how to do it, though! 😁
In the meantime, I'll remove 9fd197d so we can merge this, if you agree with the implementation.

**Comment by bingocaller** [comment]
@shinriyo I've removed 9fd197d, so this should be good to merge if you agree with converting the simple alias functions to abbreviations.

**Pull request merged**
